<?php

// autoload_namespaces.php generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Vodacek\\Forms\\Controls\\DateInput' => $vendorDir . '/voda/date-input',
);
